### ISSUE TITLE
Rerendering issue under function view

### ISSUE THREAD

**Issue by spade1015** [the-jet-trio/fprime-editor#31]
There is still a rerendering issue under function view. For example:
1. Go to "Ref.REFTelemetry" under function view
2. Delete "Ref.chanTlm"
3. Delete "Ref.SG1"
4. Delete "Ref.SG2". Rerender happens.
5. Delete "Ref.SG3". Rerender happens.
6. Delete "Ref.SG4". Rerender happens.

**Comment by weicfd** [comment]
lower priority
