### ISSUE TITLE
When a component instantiated, it does not have a default base ID.

### ISSUE THREAD

**Issue by spade1015** [the-jet-trio/fprime-editor#35]
When a component instantiated, it does not have a default base ID. If the user instantiates a component and wants to rename it, he/she will have to assign a base ID first (or the update on the attribute panel is rejected since the base ID is empty). 

Also, the error message ("Please use valid input!") is ambiguous since the user does not know which field is invalid.

**Comment by rudylyu** [comment]
Fixed.

**Comment by spade1015** [comment]
Right now the default base ID is all -1. Is this intended?

**Comment by spade1015** [comment]
When a component is instantiated, the default base ID window is "DefaultBaseID", which does not make sense (it should be a number). Base ID window is optional, so I think we can leave that out for default. But we might have to assign a reasonable default base ID.

**Comment by rudylyu** [comment]
fixed.
